version: "3.1"


services:
    php:
       build:
           context: .
           dockerfile: Dockerfile
       container_name: learnl     
       ports:
            - 80:80
       volumes:
            - ./src:/var/www/html/
            - ./src/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./src/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
          #  - ./src/docker/apache_conf/:/etc/apache2/
    db:
       image: mysql
       command: --default-authentication-plugin=mysql_native_password
       restart: always
       environment: 
            MYSQL_ROOT_PASSWORD: 123456
       volumes:
            - mysql-data:/var/lib/mysql 
    adminer:
       image: adminer
       restart: always
       ports:
            - 8080:8080
volumes:
    mysql-data: